language: node_js
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install: "nvm install \"$(jq -r '.engines.node' package.json)\" && node --version"
cache:
  directories:
    - node_modules
