language: node_js
node_js:
- '8.11.X'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_deploy: "pip install awscli --upgrade --user"
cache:
  yarn: true
  directories:
  - node_modules
